POST http://localhost:8000/users/register
Content-Type: application/json

{
  "fullName": "SolihCoder",
  "login": "SolihCoder",
  "password": "123"
}

###

POST http://localhost:8000/users/login
Content-Type: application/json

{
  "login": "SolihCoder",
  "password": "123"
}

###

DELETE http://localhost:8000/books/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzgxNzg2NjY2LCJleHAiOjE3ODE3OTAyNjZ9.CqejCXZsmgDtp0VeR2eAX4iW-xdfBqPXhi76Q4iL6jk

###
GET http://localhost:8000/books

###

POST http://localhost:8000/book-categories/create
Content-Type: application/json

{
  "title": "tarix"
}

###

PATCH http://localhost:8000/book-categories/update/2
Content-Type: application/json

{
  "title": "Tarix"
}

###

GET http://localhost:8000/book-categories/list?page=2&size=3&search=a

